[server]
# Change the type of file watcher used by Streamlit, or turn it off
# completely.
#
# Allowed values:
# - "auto"     : Streamlit will attempt to use the watchdog module, and
#                falls back to polling if watchdog isn't available.
# - "watchdog" : Force Streamlit to use the watchdog module.
# - "poll"     : Force Streamlit to always use polling.
# - "none"     : Streamlit will not watch files.
#
# Default: "auto"
fileWatcherType = "poll"